# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recorder.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_teknobol_Recorder(object):
    def setupUi(self, teknobol_Recorder):
        teknobol_Recorder.setObjectName("teknobol_Recorder")
        teknobol_Recorder.resize(343, 257)
        self.centralwidget = QtWidgets.QWidget(teknobol_Recorder)
        self.centralwidget.setObjectName("centralwidget")
        self.startRecording = QtWidgets.QPushButton(self.centralwidget)
        self.startRecording.setGeometry(QtCore.QRect(10, 160, 321, 41))
        self.startRecording.setObjectName("startRecording")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 321, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lne_FileName = QtWidgets.QLineEdit(self.widget)
        self.lne_FileName.setObjectName("lne_FileName")
        self.horizontalLayout.addWidget(self.lne_FileName)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.cmb_FileType = QtWidgets.QComboBox(self.widget)
        self.cmb_FileType.setObjectName("cmb_FileType")
        self.cmb_FileType.addItem("")
        self.cmb_FileType.addItem("")
        self.horizontalLayout_2.addWidget(self.cmb_FileType)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.cmb_Resolution = QtWidgets.QComboBox(self.widget)
        self.cmb_Resolution.setObjectName("cmb_Resolution")
        self.cmb_Resolution.addItem("")
        self.horizontalLayout_3.addWidget(self.cmb_Resolution)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.cmb_FPS = QtWidgets.QComboBox(self.widget)
        self.cmb_FPS.setObjectName("cmb_FPS")
        self.cmb_FPS.addItem("")
        self.cmb_FPS.addItem("")
        self.cmb_FPS.addItem("")
        self.cmb_FPS.addItem("")
        self.cmb_FPS.addItem("")
        self.horizontalLayout_5.addWidget(self.cmb_FPS)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        teknobol_Recorder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(teknobol_Recorder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 343, 21))
        self.menubar.setObjectName("menubar")
        teknobol_Recorder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(teknobol_Recorder)
        self.statusbar.setObjectName("statusbar")
        teknobol_Recorder.setStatusBar(self.statusbar)

        self.retranslateUi(teknobol_Recorder)
        QtCore.QMetaObject.connectSlotsByName(teknobol_Recorder)

    def retranslateUi(self, teknobol_Recorder):
        _translate = QtCore.QCoreApplication.translate
        teknobol_Recorder.setWindowTitle(_translate("teknobol_Recorder", "Teknobol Recorder"))
        self.startRecording.setText(_translate("teknobol_Recorder", "Kaydı Başlat"))
        self.label.setText(_translate("teknobol_Recorder", "Dosya Adı"))
        self.cmb_FileType.setItemText(0, _translate("teknobol_Recorder", ".avi"))
        self.cmb_FileType.setItemText(1, _translate("teknobol_Recorder", ".mp4"))
        self.label_2.setText(_translate("teknobol_Recorder", "Çözünürlük"))
        self.cmb_Resolution.setItemText(0, _translate("teknobol_Recorder", "1920, 1080"))
        self.label_3.setText(_translate("teknobol_Recorder", "FPS"))
        self.cmb_FPS.setItemText(0, _translate("teknobol_Recorder", "30.0"))
        self.cmb_FPS.setItemText(1, _translate("teknobol_Recorder", "45.0"))
        self.cmb_FPS.setItemText(2, _translate("teknobol_Recorder", "60.0"))
        self.cmb_FPS.setItemText(3, _translate("teknobol_Recorder", "75.0"))
        self.cmb_FPS.setItemText(4, _translate("teknobol_Recorder", "90.0"))

